# Generated by Django 4.2.11 on 2026-04-01 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount (must be positive)', max_digits=12)),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], help_text='Income or Expense', max_length=10)),
                ('category', models.CharField(choices=[('salary', 'Salary'), ('freelance', 'Freelance'), ('investment', 'Investment'), ('grocery', 'Grocery'), ('utilities', 'Utilities'), ('transport', 'Transport'), ('entertainment', 'Entertainment'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('other', 'Other')], help_text='Transaction category', max_length=50)),
                ('date', models.DateField(help_text='Transaction date')),
                ('description', models.TextField(blank=True, help_text='Transaction description/notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('user', models.ForeignKey(help_text='User who owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='financial_records', to='users.user')),
            ],
            options={
                'verbose_name': 'Financial Record',
                'verbose_name_plural': 'Financial Records',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='records_fin_user_id_69b2d4_idx'), models.Index(fields=['user', 'type'], name='records_fin_user_id_24faf6_idx'), models.Index(fields=['user', 'category'], name='records_fin_user_id_fff57e_idx')],
            },
        ),
    ]
